def PROJECT_DIR = "project5"
def JAVA_APP_DIR = "${PROJECT_DIR}/java-app"
def CONTROL_NODE = "root@64.226.86.32"

pipeline {
    agent any
    tools {
        gradle 'gradle'
    }

    stages {

        stage('Configure Ansible control node') {
            steps {
                echo 'Installing Ansible'
                script {
                    dir(PROJECT_DIR) {
                        sshagent(['dev-ops-bootcamp']) {
                            def shellCmd = "./configure-control-node.sh"

                            sh "scp -o StrictHostKeyChecking=no configure-control-node.sh ${CONTROL_NODE}:/root"
                            sh "ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} ${shellCmd}"
                        }
                    }
                }
            }
        }

        stage('Build Jar file') {
            steps {
                echo 'Building Jar file'
                dir(JAVA_APP_DIR) {
                    sh 'gradle build'
                }
            }
        }

        stage('Copy files to Ansible control node') {
            steps {
                echo 'Copying files to Ansible control node'
                dir(PROJECT_DIR) {
                    withCredentials([
                        sshUserPrivateKey(
                            credentialsId: 'dev-ops-bootcamp',
                            keyFileVariable: 'SSH_KEY_FILE'
                        ),
                        file(
                            credentialsId: 'aws_credentials',
                            variable: 'AWS_CREDENTIALS_FILE'
                        )
                    ]) {
                        sshagent(['dev-ops-bootcamp']) {
                            sh "ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} mkdir -p /root/ansible"
                            sh "ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} mkdir -p /root/.aws"
                            sh "scp -o StrictHostKeyChecking=no ansible-remote/* ${CONTROL_NODE}:/root/ansible"
                            sh "scp -o StrictHostKeyChecking=no ${SSH_KEY_FILE} ${CONTROL_NODE}:/root/.ssh/dev-ops-bootcamp.pem"
                            sh "scp -o StrictHostKeyChecking=no ${AWS_CREDENTIALS_FILE} ${CONTROL_NODE}:/root/.aws/credentials"
                            sh "ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} chmod 600 /root/.ssh/dev-ops-bootcamp.pem"
                            sh "ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} chmod 600 /root/.aws/credentials"
                            sh "scp -o StrictHostKeyChecking=no java-app/build/libs/build-tools-exercises-1.0-SNAPSHOT.jar ${CONTROL_NODE}:/root/ansible/app.jar"
                        }
                    }
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                echo 'Running Ansible playbook'
                sshagent(['dev-ops-bootcamp']) {
                    sh """ssh -o StrictHostKeyChecking=no ${CONTROL_NODE} 'cd ansible && ansible-playbook -i inventory_aws_ec2.yaml -e "@vars.yaml" configure_app_instances.yaml'"""
                }
            }
        }
    }
}
