def gv
def projectDir = "project3/java-app"

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage("init") {
            steps {
                script {
                    dir(projectDir) {
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    dir(projectDir) {
                        gv.buildJar()
                    }
                }
            }
        }

        stage("build image") {
            steps {
                script {
                    dir(projectDir) {
                        gv.buildImage("aam123/java-app:capstone3")
                    }
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
