apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_user: {{ .Values.database.user }}
  db_pass: {{ .Values.database.pass }}
  db_name: {{ .Values.database.name }}
  db_root_pass: {{ .Values.database.rootPass }}
