apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      name: java-app
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: {{ .Values.app.image}}:{{ .Values.app.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_name
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_server
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mysql
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: java-app
  policyTypes:
    - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: java-app
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - {}
